class Movie {
  String nameMovie, urlImage, releaseDate , description ;
  int id;
  Movie({required this.id,required this.nameMovie, required this.urlImage , required this.releaseDate ,required this.description});
}
List<Movie> DATA_MOVIE= [
  Movie(id: 1,nameMovie: " ĐỐI MẶT TỬ THÙ", urlImage: "assets/images/venom-2-doi-mat-tu-thu-54064-thumbnail.jpg", releaseDate: "15-10-2021", description: "Venom: Đối mặt tử thù là phim siêu anh hùng Mỹ sắp ra mắt dựa trên nhân vật Venom, được Columbia Pictures cùng với Marvel và Tencent Pictures đồng sản xuất. Được phân phối bởi Sony Pictures Releasing, phim sẽ là phần hậu truyện của Venom (2018). Phim được đạo diễn bởi Andy Serkis từ kịch bản của Kelly Marcel, dựa theo cốt truyện cô viết cùng với Tom Hardy (diễn viên thủ vai Venom). Phim quy tụ dàn diễn viên gồm Tom Hardy, Michelle Williams, Naomie Harris, Reid Scott, Stephen Graham và Woody Harrelson"),
  Movie(id: 2,nameMovie: "GIẢI CỨU ‘GUY’", urlImage: "assets/images/611727c62b3cf.jpg", releaseDate: "15-10-2021", description: "Venom: Đối mặt tử thù là phim siêu anh hùng Mỹ sắp ra mắt dựa trên nhân vật Venom, được Columbia Pictures cùng với Marvel và Tencent Pictures đồng sản xuất. Được phân phối bởi Sony Pictures Releasing, phim sẽ là phần hậu truyện của Venom (2018). Phim được đạo diễn bởi Andy Serkis từ kịch bản của Kelly Marcel, dựa theo cốt truyện cô viết cùng với Tom Hardy (diễn viên thủ vai Venom). Phim quy tụ dàn diễn viên gồm Tom Hardy, Michelle Williams, Naomie Harris, Reid Scott, Stephen Graham và Woody Harrelson"),
  Movie(id: 3,nameMovie: "DẠ QUỶ RỪNG SÂU", urlImage: "assets/images/da-quy-rung-sau-54434-thumbnail-250x350.jpg", releaseDate: "15-10-2021", description: "Venom: Đối mặt tử thù là phim siêu anh hùng Mỹ sắp ra mắt dựa trên nhân vật Venom, được Columbia Pictures cùng với Marvel và Tencent Pictures đồng sản xuất. Được phân phối bởi Sony Pictures Releasing, phim sẽ là phần hậu truyện của Venom (2018). Phim được đạo diễn bởi Andy Serkis từ kịch bản của Kelly Marcel, dựa theo cốt truyện cô viết cùng với Tom Hardy (diễn viên thủ vai Venom). Phim quy tụ dàn diễn viên gồm Tom Hardy, Michelle Williams, Naomie Harris, Reid Scott, Stephen Graham và Woody Harrelson"),
  Movie(id: 4,nameMovie: "HÀNH TINH CÁT", urlImage: "assets/images/hanh-tinh-cat-54373-thumbnail-250x350.jpg", releaseDate: "15-10-2021", description: "Venom: Đối mặt tử thù là phim siêu anh hùng Mỹ sắp ra mắt dựa trên nhân vật Venom, được Columbia Pictures cùng với Marvel và Tencent Pictures đồng sản xuất. Được phân phối bởi Sony Pictures Releasing, phim sẽ là phần hậu truyện của Venom (2018). Phim được đạo diễn bởi Andy Serkis từ kịch bản của Kelly Marcel, dựa theo cốt truyện cô viết cùng với Tom Hardy (diễn viên thủ vai Venom). Phim quy tụ dàn diễn viên gồm Tom Hardy, Michelle Williams, Naomie Harris, Reid Scott, Stephen Graham và Woody Harrelson"),
  Movie(id: 5,nameMovie: "NGÔI NHÀ DƯỚI NƯỚC", urlImage: "assets/images/ngoi-nha-duoi-nuoc-54785-thumbnail-250x350.jpg", releaseDate: "15-10-2021", description: "Venom: Đối mặt tử thù là phim siêu anh hùng Mỹ sắp ra mắt dựa trên nhân vật Venom, được Columbia Pictures cùng với Marvel và Tencent Pictures đồng sản xuất. Được phân phối bởi Sony Pictures Releasing, phim sẽ là phần hậu truyện của Venom (2018). Phim được đạo diễn bởi Andy Serkis từ kịch bản của Kelly Marcel, dựa theo cốt truyện cô viết cùng với Tom Hardy (diễn viên thủ vai Venom). Phim quy tụ dàn diễn viên gồm Tom Hardy, Michelle Williams, Naomie Harris, Reid Scott, Stephen Graham và Woody Harrelson"),
  Movie(id: 6,nameMovie: "NHỮNG VỊ THÁNH CỦA NEWARK", urlImage: "assets/images/nhung-vi-thanh-cua-newark-54336-thumbnail-250x350.jpg", releaseDate: "15-10-2021", description: "Venom: Đối mặt tử thù là phim siêu anh hùng Mỹ sắp ra mắt dựa trên nhân vật Venom, được Columbia Pictures cùng với Marvel và Tencent Pictures đồng sản xuất. Được phân phối bởi Sony Pictures Releasing, phim sẽ là phần hậu truyện của Venom (2018). Phim được đạo diễn bởi Andy Serkis từ kịch bản của Kelly Marcel, dựa theo cốt truyện cô viết cùng với Tom Hardy (diễn viên thủ vai Venom). Phim quy tụ dàn diễn viên gồm Tom Hardy, Michelle Williams, Naomie Harris, Reid Scott, Stephen Graham và Woody Harrelson")
];
